### ISSUE TITLE
script breaks on "&" character (unicode)

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#186]
As seen in https://github.com/Cockatrice/Magic-Spoiler/pull/185 or https://github.com/Cockatrice/Magic-Spoiler/commit/626457372ba223e6ca6f2811a18c03f95f791ab8.

According to @dev-id the script breaks on the `&` in the card `Sword of Dungeons & Dragons` from Unstable.
Same problem could exist for other chars that we didn't run into yet.

---

Error from [travis](https://travis-ci.org/Cockatrice/Magic-Spoiler/builds/306357029?utm_source=github_status&utm_medium=notification):
```
Running script...

Setting preset dumpXML to value True

Removing card scraped from MTGS RSS but not in their gallery: By  Means

Removing card scraped from MTGS RSS but not in their gallery: More Less

Traceback (most recent call last):

  File "main.py", line 131, in <module>

    mtgjson = spoilers.get_image_urls(mtgs, presets['isfullspoil'], setinfo)  # get images

  File "/home/travis/build/Cockatrice/Magic-Spoiler/spoilers.py", line 384, in get_image_urls

    if 'wizards.com' in c['url']:

TypeError: argument of type 'NoneType' is not iterable
```

---

It breaks for mtgs and scryfall.

**Data from spoiler.rss at mtgs:**
```
<item>
      <guid isPermaLink="false">29752</guid>
      <link>http://www.mtgsalvation.com/cards/unstable/29752-sword-of-dungeons-dragons</link>
      <title>Sword of Dungeons &amp; Dragons</title>
      <description>

&lt;b&gt;Name:&lt;/b&gt; &lt;b&gt;Sword of Dungeons &amp; Dragons&lt;/b&gt;&lt;br&gt;
Set: Unstable&lt;br&gt;
Cost: 3&lt;br&gt;
Type: Artifact - Equipment&lt;br&gt;

Rules Text: Equipped creature gets +2/+2 and has protection from Rogues and from Clerics.

Whenever equipped creature deals combat damage to a player, create a 4/4 gold Dragon creature token with flying and roll a d20. If you roll a 20, repeat this process.

Equip {2}&lt;br&gt;

Illus. Chris Rahn&lt;br&gt;
Rarity: Mythic Rare&lt;br&gt;
Set Number: #163/216&lt;br&gt;
&lt;br&gt;</description>
      <pubDate>Sat, 11 Nov 2017 00:11:38 Z</pubDate>
      <a10:updated>2017-11-11T00:11:38Z</a10:updated>
    </item>
```

**Data from scryfall api**
(https://api.scryfall.com/cards/search?format=json&order=name&page=2&q=e%3Aust)
```
{
      "object": "card",
      "id": "bacce818-96b4-4b6f-97c4-74a22c8d9afb",
      "multiverse_ids": [],
      "name": "Sword of Dungeons & Dragons",
      "uri": "https://api.scryfall.com/cards/ust/163",
      "scryfall_uri": "https://scryfall.com/card/ust/163?utm_source=api",
      "layout": "normal",
      "highres_image": false,
      "image_uris": {
        "small": "https://img.scryfall.com/cards/small/en/ust/163.jpg?1510970518",
        "normal": "https://img.scryfall.com/cards/normal/en/ust/163.jpg?1510970518",
        "large": "https://img.scryfall.com/cards/large/en/ust/163.jpg?1510970518",
        "png": "https://img.scryfall.com/cards/png/en/ust/163.png?1510970518",
        "art_crop": "https://img.scryfall.com/cards/art_crop/en/ust/163.jpg?1510970518",
        "border_crop": "https://img.scryfall.com/cards/border_crop/en/ust/163.jpg?1510970518"
      },
      "cmc": 3,
      "type_line": "Artifact — Equipment",
      "oracle_text": "Equipped creature gets +2/+2 and has protection from Rogues and from Clerics.\nWhenever equipped creature deals combat damage to a player, create a 4/4 gold Dragon creature token with flying and roll a d20 (a twenty-sided die). If you roll a 20, repeat this process.\nEquip {2}",
      "mana_cost": "{3}",
      "colors": [],
      "color_identity": [],
      "legalities": {
        "standard": "not_legal",
        "frontier": "not_legal",
        "modern": "not_legal",
        "pauper": "not_legal",
        "legacy": "not_legal",
        "penny": "not_legal",
        "vintage": "not_legal",
        "duel": "not_legal",
        "commander": "not_legal",
        "1v1": "not_legal",
        "future": "not_legal"
      },
      "reserved": false,
      "reprint": true,
      "set": "ust",
      "set_name": "Unstable",
      "set_uri": "https://api.scryfall.com/cards/search?q=%2B%2Be%3Aust",
      "set_search_uri": "https://api.scryfall.com/cards/search?q=%2B%2Be%3Aust",
      "scryfall_set_uri": "https://scryfall.com/sets/ust?utm_source=api",
      "rulings_uri": "https://api.scryfall.com/cards/ust/163/rulings",
      "prints_search_uri": "https://api.scryfall.com/cards/search?order=set&q=%2B%2B%21%22Sword+of+Dungeons+%26+Dragons%22",
      "collector_number": "163",
      "digital": false,
      "rarity": "mythic",
      "illustration_id": "52c495e2-0e36-44de-a508-498fbd34fa8d",
      "artist": "Chris Rahn",
      "frame": "2015",
      "full_art": false,
      "border_color": "silver",
      "timeshifted": false,
      "colorshifted": false,
      "futureshifted": false,
      "usd": "2.49",
      "eur": "2.01",
      "related_uris": {
        "tcgplayer_decks": "http://decks.tcgplayer.com/magic/deck/search?contains=Sword+of+Dungeons+%26+Dragons&page=1&partner=Scryfall",
        "edhrec": "http://edhrec.com/route/?cc=Sword+of+Dungeons+%26+Dragons",
        "mtgtop8": "http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Sword+of+Dungeons+%26+Dragons"
      },
      "purchase_uris": {
        "amazon": "https://www.amazon.com/gp/search?ie=UTF8&index=toys-and-games&keywords=Sword+of+Dungeons+%26+Dragons&tag=scryfall-20",
        "ebay": "http://rover.ebay.com/rover/1/711-53200-19255-0/1?campid=5337966903&icep_catId=19107&icep_ff3=10&icep_sortBy=12&icep_uq=Sword+of+Dungeons+%26+Dragons&icep_vectorid=229466&ipn=psmain&kw=lg&kwid=902099&mtid=824&pub=5575230669&toolid=10001",
        "tcgplayer": "http://store.tcgplayer.com/magic/unstable/sword-of-dungeons-and-dragons?partner=Scryfall",
        "magiccardmarket": "https://www.cardmarket.com/Magic/Products/Singles/Unstable/Sword+of+Dungeons+%26+Dragons?referrer=scryfall",
        "cardhoarder": "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Sword+of+Dungeons+%26+Dragons&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
        "card_kingdom": "https://www.cardkingdom.com/catalog/item/215563?partner=scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall",
        "mtgo_traders": "http://www.mtgotraders.com/store/search.php?q=Sword+of+Dungeons+%26+Dragons&referral=scryfall",
        "coolstuffinc": "http://www.coolstuffinc.com/p/Magic%3A+The+Gathering/Sword+of+Dungeons+%26+Dragons?utm_source=scryfall"
      }
    },
```

<br>

Linking https://github.com/Cockatrice/Magic-Spoiler/issues/151

**Comment by tooomm** [comment]
No longer valid
