### ISSUE TITLE
if no set is enabled --> script brakes

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#192]
As long as there are no input data (`noRSS: false` for mtgs and others as well I assume), the script simply breaks instead dealing with the no-data-available and printing a useful hint while it should always *pass* in that case!

```
Running script...

Setting preset dumpXML to value True

Not processing set(s) with no cards: ['RIX', 'A25', 'DOM', 'M19']

Traceback (most recent call last):

  File "main.py", line 172, in <module>

    save_setjson(combinedjson, 'spoiler')

  File "main.py", line 63, in save_setjson

    with io.open('out/' + filename + '.json', 'w', encoding='utf8') as json_file:

IOError: [Errno 2] No such file or directory: 'out/spoiler.json'
```

Examples:
https://travis-ci.org/Cockatrice/Magic-Spoiler/builds/310537354
https://travis-ci.org/Cockatrice/Magic-Spoiler/builds/310537312

**Comment by tooomm** [comment]
This seems to be no issue when Travis runs from master!
See https://travis-ci.org/Cockatrice/Magic-Spoiler/builds/328793688, Travis cron passes even after RIX was included into mtgjson at that point (as written in the logs), but `set_info` still had the outdated set included: https://github.com/Cockatrice/Magic-Spoiler/blob/050711b393d0fdecd1fa537f3716a51d4f74ee35/set_info.yml#L52-L62

All builds on branches or PR's fail though with the message in the starting post.
Example failing build: https://travis-ci.org/Cockatrice/Magic-Spoiler/builds/328151561
The two linked builds in the starting post are from a PR and branch, too!
